spring:
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
service:
  number: 7777777
  url: https://webrisk.googleapis.com/v1eap1:evaluateUri
flyway:
  user: ${spring.datasource.username}
  password: ${spring.datasource.password}
  schemas: PUBLIC
  url: ${spring.datasource.url}
  locations: classpath:db/migration